program: statements*;
statement: expression ';';
expression: expression_binary;
expression_binary: primary ( ('+' | '-' | '*' | '/' | '%') primary)*;
primary: IDENTIFIER | NUMBER | '(' expression ')';
